# Generated by Django 5.1.6 on 2025-03-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_categoria_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='avatar',
            field=models.ImageField(blank=True, default='home/default_avatar.png', null=True, upload_to='avatars/'),
        ),
    ]
